### ISSUE TITLE
 Suddenly falls

### ISSUE THREAD

**Issue by monoflash** [kataras/go-websocket#11]
I writing here, as in "iris-contrib/websocket" issue is disabled

I use "github.com/iris-contrib/websocket"
It is made on the basis of "gorilla/websocket"

**If you can, remove the gorilla\* and don't use "gorilla/{_anything_}" !**

Use "golang.org/x/net/websocket"!

"github.com/iris-contrib/websocket" suddenly falls:
![2016-10-18 13 06 45](https://cloud.githubusercontent.com/assets/6280295/19473779/03aff5aa-953e-11e6-84a0-618ecd90664b.png)

**Comment by ghost** [comment]
Dear monoflash

> I writing here, as in "iris-contrib/websocket" issue is disabled

I don't know why this happened, it's fixed, now you can post an issue [here](https://github.com/iris-contrib/websocket) too,thanks for the info

Could you please re-post it with the panic flow? what makes produces this?
Your panics shows

``` go
    if err := c.conn.SetWriteDeadline(deadline); err != nil {
        return err
    }
```

but conn is not nil because it's called before, if it was it should panic before, so please **upgrade iris-contrib/websocket** and try again, if that didnt fixed it then post your source code among with the program flow which produces this panic, please.

Thanks,
kataras

**Comment by monoflash** [comment]
The error occurs on the not entirely clear reasons. 
I noticed that a mistake can be repeated if put to sleep and then wake up Mac OS. But the error does not occur with every time when wake up Mac OS.
As you can see in the screenshot in a panic is not my code, something falls within the iris or websocket
Probably blame SetWriteDeadline function because of the sleep time passes and immediately after waking up connection must be terminated correctly without panic

In the screenshot that all golang panic flow shown.
The program ends with an error code 2

```
go version go1.7.1 darwin/amd64
```

![2016-10-19 12 05 55](https://cloud.githubusercontent.com/assets/6280295/19512599/bd64f1c0-95fd-11e6-9ca4-d5ef06394050.png)

**Comment by kataras** [comment]
I see, we had issues with MacOSX and safari, could you produce it with Chrome/Firefox ?

**Comment by ghost** [comment]
I see but this repository **it has nothing to do with the iris-contrib/websocket** so please, move this post there in order to discuss it, keep note that I think that you're using Safari, **Safari has problems both on gorilla and golang/x/net**

About your note: 

> If you can, remove the gorilla\* and don't use "gorilla/{anything}" !

Yes at the first I tried with golang/x/net's version, but believe me , that library has even more bugs.

iris supports hijack so you're free to use any websocket library you want and you used before iris, with some small changes.
